# This workflow increments the minor version 
# when there is a push to the main branch. It
# also creates a new release for the tag.
# 
# It does not run if the commit has been tagged,
# so that it doesn't get in to an endless loop
# when a tagged commit gets pushed.
on:
    push:
        branches:
            - main
        tags-ignore:
            - "*"         

name: Increment minor version
jobs:
    increment_minor_version:
        name: Increment minor version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                go-version: '^1.15'

            - name: Install dependencies
              run: |
                go mod vendor
                go get github.com/davidrjonas/semver-cli
                go get github.com/mitchellh/gox

            - name: Increment minor version
              run: |
                echo "Current version: $(cat version.txt)"
                semver-cli inc minor $(cat version.txt) > version.txt
                echo "New version: $(cat version.txt)"
                echo "CF_TRAVERSE_VERSION=$(cat version.txt)" >> $GITHUB_ENV 

            - name: Tag, commit, push
              uses: EndBug/add-and-commit@v5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                add: version.txt
                author_name: "GitHub Actions on behalf of Andy Hunt"
                author_email: "github@andyhunt.me"
                message: "Bump version to ${{ env.CF_TRAVERSE_VERSION }}"
                tag: "${{ env.CF_TRAVERSE_VERSION }} --force"

            - name: Compile release
              run: make release

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ env.CF_TRAVERSE_VERSION }}
                release_name: "Version ${{ env.CF_TRAVERSE_VERSION }}"
                draft: false
                prerelease: false

            - name: Upload assets
              id: upload_assets
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh release upload "${CF_TRAVERSE_VERSION}" ./bin/release/*
