---
name: PR
on: pull_request
permissions:
  contents: read



jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ "^1", "^1.17" ]
    steps:
      - uses: actions/checkout@v2 # Trusted creator
      - uses: actions/setup-go@v2 # Trusted creator
        with:
          check-latest: true
          go-version: ${{ matrix.go_version }}

      - name: "Run tests"
        run: make test