# This workflow runs the suite of tests when a PR is 
# created or modified.
on: pull_request
name: Pull Request
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Install dependencies
        run: |
          go mod vendor
          go get github.com/davidrjonas/semver-cli

      - name: Run tests
        run: go test ./...

      - name: Install CF CLI
        run: |
          wget -O cf-cli.tar.gz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7.2.0&source=github-rel"
          tar xzf cf-cli.tar.gz
          chmod +x cf7
          sudo mv cf /usr/local/bin/cf
          sudo mv cf7 /usr/local/bin/cf7

      - name: Test plugin install
        run: make install
